### ISSUE TITLE
Popovers and Tooltips

### ISSUE THREAD

**Issue by mcraiganthony** [rhinogram/rhinostyle#35]
Build popover and tooltip component.

**Comment by zslabs** [comment]
Just so we have a note of it here, this issue will be pending until we have some more time to look into either [react-portal](https://github.com/tajo/react-portal) or when [react-fiber](http://isfiberreadyyet.com/) is released.

**Comment by zslabs** [comment]
This will be able to be revisited once https://github.com/rhinogram/rhinostyle/pull/73 is in.

**Comment by zslabs** [comment]
Tooltips have been added with https://github.com/rhinogram/rhinostyle/pull/86

Popovers could be a great addition as well; we'll see how the needs of the app evolve. If we do go down that road, I'd love to look into a library like [popper](https://popper.js.org/) to help us with some of our "auto-placement" issues based on available screen real-estate; not only for popovers, but also tooltips and dropdowns.
