### ISSUE TITLE
Investigate an alternative to resize library used in MessageBox

### ISSUE THREAD

**Issue by BlakeGuilloud** [rhinogram/rhinostyle#67]
The library we use to resize our MessageBox component is causing serious lag to windows machines running even the latest versions of firefox. The issue seems to stem from the nested component architecture employed by our front end application. When placed outside of the InboxThread component, the MessageBox seems to respond as designed with minimal lag; however, whatever this library is doing is not playing nice with either the rerendering process that React does naturally, or potentially the way we are using flexbox (per zslabs).

### Environment
- [x] Dev
- [x] Production

### Is this issue browser or OS specific?
Most prevalent in Firefox on windows machines.

### Steps to reproduce
1. Open Rhinogram with Firefox on windows.
2. Type into the MessageBox.
3. Notice the lag.

**Comment by zslabs** [comment]
@alexgsummer [Here's the branch](https://github.com/rhinogram/rhinostyle/tree/zach/autoresize) and [comparison between that branch and master](https://github.com/rhinogram/rhinostyle/compare/zach/autoresize?expand=1). I tested typing, pasting (keyboard and right-click) and inserting a template successfully. Jumping into meeting, but will hop back on to also test performance as well.

**Comment by zslabs** [comment]
Address in https://github.com/rhinogram/rhinostyle/pull/68
